spring:
  application:
    name: turbine
server:
  port: 8080
management:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: eureka-producer-feign-hystrix
  cluster-name-expression: new String("default")
  combine-host-port: true